"""
Step-by-Step Guide to Upload SAM2 to HuggingFace Hub

Follow these steps:
"""

print("=" * 70)
print("🚀 HUGGINGFACE HUB SETUP - STEP BY STEP")
print("=" * 70)
print()

print("STEP 1: Create HuggingFace Account (if you don't have one)")
print("-" * 70)
print("1. Go to: https://huggingface.co/join")
print("2. Sign up with your email")
print("3. Verify your email")
print()

print("STEP 2: Create an Access Token")
print("-" * 70)
print("1. Go to: https://huggingface.co/settings/tokens")
print("2. Click 'New token'")
print("3. Name: 'ocr-model-upload'")
print("4. Type: Select 'Write' (allows uploads)")
print("5. Click 'Generate token'")
print("6. COPY the token (you'll need it in the next step)")
print()

print("STEP 3: Login with Token")
print("-" * 70)
print("Run this command and paste your token when prompted:")
print()
print("    huggingface-cli login")
print()
print("Or use the new command:")
print("    hf auth login")
print()
print("When it asks for the token, paste it (Right-click to paste)")
print()

print("STEP 4: Upload SAM2 Model")
print("-" * 70)
print("Run this script:")
print()
print("    python backend/huggingface_hosting.py upload")
print()
print("This will:")
print("  - Create a new repo: firasayari10/sam2-medical-ocr")
print("  - Upload sam2_hiera_large.pt (856 MB)")
print("  - Make it public (free) or private (requires Pro)")
print()

print("STEP 5: Update Environment Variable")
print("-" * 70)
print("Add to your .env file:")
print()
print('    SAM2_HF_REPO="firasayari10/sam2-medical-ocr"')
print()
print("Or set in PowerShell:")
print()
print('    $env:SAM2_HF_REPO="firasayari10/sam2-medical-ocr"')
print()

print("STEP 6: Test It!")
print("-" * 70)
print("Start your server:")
print()
print("    python backend/main_agent_api.py")
print()
print("It will automatically download SAM2 from HuggingFace on first run!")
print()

print("=" * 70)
print("✨ THAT'S IT! Your models are now hosted for FREE on HuggingFace!")
print("=" * 70)
print()
print("OPTIONAL: Make Repository Private")
print("-" * 70)
print("1. Go to: https://huggingface.co/firasayari10/sam2-medical-ocr/settings")
print("2. Scroll to 'Change repository visibility'")
print("3. Click 'Make private' (requires HF Pro subscription $9/mo)")
print()

print("=" * 70)
print()
print("Need help? Run: python backend/huggingface_hosting.py --help")
print()
